layout: post
title: Joomee Choi
logo: /assets/img/heatshot.jpg
description: "Pursuing a dual major in Computer Science and Design at Northeastern University with a passion for user experience, user interaction, and data analysis."
show_downloads: true
theme: jekyll-theme-minimal
