layout: post
title: Joomee Choi
logo: /assets/img/image.HEIC
description: "Pursuing a dual major in Computer Science and Design at Northeastern University."
show_downloads: true
theme: jekyll-theme-minimal
